name: actions-example

on: push

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: run tests
        run: ./gradlew clean test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv  
          badges-directory: build/reports/jacoco/test/html/badges

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/jacoco/test/html
