name: Example workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show text
        run: echo Some text

      - name: Addition
        run: echo 2 + 5
